### ISSUE TITLE
Code releasing.

### ISSUE THREAD

**Issue by junshengzhou** [rsy6318/CorrI2P#1]
Hi, 
Thanks for your great job! And when will you release the code?

**Comment by rsy6318** [comment]
Thanks for your conformation! We will upload our code as soon as possible

**Comment by junshengzhou** [comment]
Hi,

Thanks for sharing your code! Can you inform when is the approximate time of code releasing, since I am soooo interest in your work! ：）If the code is under cleaning up, could you please give me a copy of the core code first, such as network structure and loss function. I have also sent you an email, and am looking forward to your reply! 
Thanks again for your great job!

Best,
Junsheng

**Comment by rsy6318** [comment]
Thanks for your attention !
We are reorganize our code and will release it as soon as possible.

**Comment by rsy6318** [comment]
We have uploaded the core code, but the dataset is too big and we need time to upload it.

**Comment by junshengzhou** [comment]
That's so great! I sincerely thank you for sharing your code so quickly!!! 
Looking forward to the dataset and I fully understand that the huge dataset takes a long time to upload. Thanks again for your great job!
