### ISSUE TITLE
how to install the 'index_max'?

### ISSUE THREAD

**Issue by atomishcv** [rsy6318/CorrI2P#12]
Thanks for sharing your works， when i try to install the index_max follow SO-Net instructions，but still got the following error：
![image](https://github.com/rsy6318/CorrI2P/assets/88809942/7de642e4-b9fe-4760-b14f-8d50bdec0d50)
I use the pycharm compiler, the environment is pytorch3.9, cuda11.6, windows

**Comment by rsy6318** [comment]
It could be installed on linux OS.

**Comment by atomishcv** [comment]
thank you
