### ISSUE TITLE
How can I get 'K', 'K_P2', 'K_P3'?

### ISSUE THREAD

**Issue by VincentWPJ** [rsy6318/CorrI2P#15]
Hi, thanks for your open-sourced work.
I have converted the official KITTI images and LiDAR data to .npy form by you scripts, but I can't run the code successfully because I lack the pose related files. I only find ten .txt files in KITTI offical website and no .npz files. Can you tell me how can I get 'K', 'K_P2', 'K_P3'?
BTW, I can't download and unzip your uploaded data (I have tried many times). @rsy6318

**Comment by LoveMYChen** [comment]
请问你解决这个问题了吗？我也有同样的疑惑

**Comment by rsy6318** [comment]
I do not know if you still focus on it. I have uploaded the data, which could be downloaded successfully.

**Comment by c2k19zwh** [comment]
I have the same confuse, could you please tell me how you solve this problem?@VincentWPJ
