### ISSUE TITLE
about index_max

### ISSUE THREAD

**Issue by czxczxczxc** [rsy6318/CorrI2P#16]
I try to run the code , but i cant install index_max, no mattter use pip or conda, how can I solve it

**Comment by rsy6318** [comment]
What is the error? Did you install all requirements?

**Comment by czxczxczxc** [comment]
1. ERROR: Could not find a version that satisfies the requirement index_max (from versions: none)
ERROR: No matching distribution found for index_max
2. PackagesNotFoundError: The following packages are not available from current channels:

  - index_max

I have installed required package
maybe related to the torchversion?
mine is torch =1.12.1+cu113 ,torchvision =0.13.1+cu113, pthon =3.8.18

**Comment by liyi0219** [comment]
> I try to run the code , but i cant install index_max, no mattter use pip or conda, how can I solve it

How did you solve it in the end?

**Comment by czxczxczxc** [comment]
it's in the code, not installed by pip or conda , my fault due to my careless

**Comment by liyi0219** [comment]
> it's in the code, not installed by pip or conda , my fault due to my careless

ok，I got it . thanks
