### ISSUE TITLE
How to picture the correspondence_ours.png

### ISSUE THREAD

**Issue by atomishcv** [rsy6318/CorrI2P#17]
![correspondence_ours](https://github.com/rsy6318/CorrI2P/assets/88809942/36060e44-ce4c-4135-9ee4-1bcb7cf56894)
thank you share your code, i want to know how to draw the result with line

**Comment by atomishcv** [comment]
![test (2)](https://github.com/rsy6318/CorrI2P/assets/88809942/60beb492-4a80-49f2-a28b-e96262035358)
i draw the picture with (40,128), how to get a big picture as you show

**Comment by rsy6318** [comment]
How about increasing the resolution to (160, 512) ?
