### ISSUE TITLE
ModuleNotFoundError: No module named 'index_max'

### ISSUE THREAD

**Issue by liyi0219** [rsy6318/CorrI2P#18]
I dont know how to use index_max. I tried to use your link about DEEPI2P, but it doesnt work. What I can do?

**Comment by rsy6318** [comment]
Go [here](https://github.com/lijx10/SO-Net/tree/master/models/index_max_ext) to install this module.

**Comment by FDZ-XL** [comment]
I'm very sorry for not being able to reply to you in a timely manner. Thank you for your answer, and I wish you a happy life!
