### ISSUE TITLE
Can not download the processed NuScenes datasets

### ISSUE THREAD

**Issue by XinjunLi-ustc** [rsy6318/CorrI2P#19]
Hi Siyu, thanks for your nice work.
I noticed that the link to download the processed NuScenes datasets seems to go wrong for some reason.
Is it convenient for you to provide a new link to get the processed NuScenes datasets?
Looking forward to your reply! Thanks!

**Comment by FDZ-XL** [comment]
Hi Siyu, 
I also want to get the  processed NuScenes datasets,
Looking forward to your reply! Thanks!

**Comment by rsy6318** [comment]
I am uploading the dataset to onedrive. Please wait for a moment.

**Comment by FDZ-XL** [comment]
ok,Thank you very much.

**Comment by rsy6318** [comment]
https://portland-my.sharepoint.com/:f:/g/personal/siyuren2-c_my_cityu_edu_hk/EhCjMm7W95pEvd0W0rMZduUBvwsUfzIYT9r3opBULD8O4g?e=0XIfhq
you can download it. I also update it on README.
