### ISSUE TITLE
Data of NuScenes.

### ISSUE THREAD

**Issue by junshengzhou** [rsy6318/CorrI2P#3]
Hi,
Do you have the plan on releasing the dataset and dataloader for NuScenes experiments. Since I would like to make a more complete comparison with your great work.
Thanks for releasing your code, looking forward to your reply.

**Comment by rsy6318** [comment]
Nuscenes dataset is not very suitable for our method because its point cloud is very sparse and some dynamic objects would influence the result, as I mentioned in the manuscript. And the result in nuscenes is worse than KITTI.

**Comment by junshengzhou** [comment]
Hi,
Thanks for your quick reply! I understand that some factors may influence the results on NuScenes, and I am trying to have more comparisons with CorrI2P (e.g. NuScenes dataset). I would be very grateful if you can provide the dataset or give me some instructions on how to process the NuScenes dataset.
Thanks again for your great job!

**Comment by rsy6318** [comment]
OK, I will upload the script for NuScenes in these days.

**Comment by junshengzhou** [comment]
Thanks a lot!!

**Comment by rsy6318** [comment]
Hi, how about nuScenes? I found prepared nuScenes in my disk and I am uploading it to onedrive. It would take some time.
![微信截图_20221007122150](https://user-images.githubusercontent.com/26300755/194467326-1e99ef43-249b-47b5-99f6-3fbdbd5e02d8.png)

**Comment by junshengzhou** [comment]
Hi,
Thank you very much for your great help! I am about to conduct experiments on Nuscenes and your help came at just the right time!🙂  
I will wait your data on Nuscenes, thanks again!~

**Comment by rsy6318** [comment]
Hi, I have uploaded the nuScenes dataset, and you can use it as well as dataloader to do the test. 
But I suggest you to use some other datasets, such as indoor dataset (NYU dataet), which is more accurate than these outdoor datasets.
Thanks for your interest in our work !

**Comment by junshengzhou** [comment]
Hi,
Thanks for your kindly and timely help! I will have a try on nuScenes. And thanks for your suggestions!
Your great job inspires me a lot, looking forward to more of your excellent works!
