### ISSUE TITLE
The scripts of the processing of NuScenes

### ISSUE THREAD

**Issue by COMoER** [rsy6318/CorrI2P#4]
Dear authors,
As mentioned in issue #3, you have updated the NuScenes dataset processed. Thanks for your effort for this. However, the scripts about NuScenes you updated (in the directory `nuScenes_script`) don't include the processing code from the raw data of NuScenes to the data form used in your dataloader script `nuscenes_pc_img_dataloader.py` .  Specifically, the data form with the subfix `.npy`, which is included in the processed dataset you updated. So could you please update the processing scripts for the NuScenes dataset? This would help me a lot and make me understand more detail about the description **We used the official SDK to get the image-point cloud pairs,  where the point cloud was accumulated from the nearby frames, and the image from the current data frame** in your paper.

Thanks for your nice work and releasing of your experiment code.

**Comment by rsy6318** [comment]
Thanks for your interest.   
I just uploaded [make_dataset.py](https://github.com/rsy6318/CorrI2P/blob/main/nuScenes_script/make_dataset.py) in nuScenes_script, and you can try it.

**Comment by COMoER** [comment]
That's what I'm wondering. Thank you for your sharing!
