### ISSUE TITLE
About data generation of nuScenes.

### ISSUE THREAD

**Issue by junshengzhou** [rsy6318/CorrI2P#5]
Hi,
I am currently visualizing the images of nuScenes, but I found that when I generate a video with a set of image frames(e.g. 0-1000), the video route is not always forward, it is very concussive. However, the route on the KITTI dataset is quite normal (when I only adopt the images from left(or right) camera). I think it's the different way for generating KITTI and nuScenes dataset (is there many cameras on the nuScenes dataset and you put their captured images together?)

Looking forward to your reply, thanks for your help!

**Comment by rsy6318** [comment]
Yes, the point cloud in nuScenes is too sparse and I accumulate several frames to obtain dense point clouds. For example, the first frame point cloud is accumulated by (1,2,4,5,9) and I choose the image of 5. The second frame point cloud is accumulated by (4,6,8,9,10) and I choose the image of 4. So the image video is not always forward. 
I have uploaded the script for data preparation and you can look for the details in them.

**Comment by junshengzhou** [comment]
I see, thanks for your detailed reply!
